config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  get 'sessions/new'

  root 'pages#index'
  get 'pages/help'

  resources :users

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :books
  
  get 'search', to: 'books#search'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :genre, presence: true
  validates :image, presence: true
  belongs_to :user
  
  mount_uploader :image, ImageUploader
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  
  has_secure_password
  
  has_many :books
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true)
  end

  def search
    @q = Book.search(search_params)
    @books = @q.result
  end



  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to books_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  def show
    @book = Book.find_by(id: params[:id])
  end

 def edit
   @book= Book.find_by(id: params[:id])
 end

 def update
    @book= Book.find_by(id: params[:id])
    if @book.update(book_params)
      redirect_to book_path, success:"更新しました"
    else
      flash.now[:danger]= "更新に失敗しました"
      render :edit
    end  
 end
 
 def destroy
    @book= Book.find_by(id: params[:id])
    @book.delete
    redirect_to books_path, success: "削除しました"
 end

  private
  def book_params
    params.require(:book).permit(:image, :description, :title, :genre)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email_params)
    if user && user.authenticate(password_params[:password])
      log_in(user)
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

 def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
 end

  private
   def email_params
    params.require(:session).permit(:email)
   end
  
  def password_params
    params.require(:session).permit(:password)
  end
  
  
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user= User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
       redirect_to root_path, success: "登録が完了しました"
       
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
      
    end
  end
  
  
  
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
    
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="book-new-wrapper" >
  <div class="container">
    <div class="row">
        <h1 class="text-center">情報更新</h1>
        <%= form_for @book do |f| %>
          <div class="form-group">
            <%= f.label :genre, "本のジャンル" %>
            <%= f.select :genre, [["文学", "文学"], ["趣味", "趣味"],  ["ビジネス", "ビジjネス"]] %>
          </div>
          <div class="form-group">
            <%= f.label :title, "本のタイトル" %>
            <%= f.text_area :title, class: "form-control"%>
          </div>
        
          <div class="form-group">
            <%= f.label :image, "イメージ画像" %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :description, "コメント" %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="book-index-wrapper">
  <%= search_form_for @q do |f| %>
    <%= f.label :title_or_description_or_genre, "本の検索" %>
    <%= f.search_field :title_or_description_or_genre_cont %>
    <%= f.submit "検索" %>
  <% end %>
  
  
    <div class="container">
      <% @books.each do |book| %>
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="book-index-single">
              <h2 class="book-author">
                <%= link_to book_path(id: book.id) do %>
                  <%= book.title %>
                <% end %>
              </h2>
              <%= link_to book_path(id: book.id) do %>
                <%= image_tag book.image.url, class: "index-image" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/books/new.html.erb
<div class="book-new-wrapper" >
  <div class="container">
    <div class="row">
        <h1 class="text-center">本の登録</h1>
        <%= form_for @book do |f| %>
          <div class="form-group">
            <%= f.label :genre, "本のジャンル" %>
            <%= f.select :genre, [["文学", "文学"], ["趣味", "趣味"],  ["ビジネス", "ビジネス"], ["その他", "その他"]],  :prompt => "選択してください" %>
          </div>
          
          
          
          <div class="form-group">
            <%= f.label :title, "本のタイトル" %>
            <%= f.text_area :title, class: "form-control"%>
          </div>
        
          <div class="form-group">
            <%= f.label :image, "イメージ画像" %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :description, "コメント" %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="book-index-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="book-index-single">
          <h2 class="book-author">
            タイトル：<%= @book.title %>
          </h2>
          <%= image_tag @book.image.url, class: "index-image" %>
          <div class= show-genre>
            ジャンル：<%= @book.genre %>
          </div>
          <div class= show-descriprion>
            コメント：<%= @book.description %>
          </div>
          <%=link_to edit_book_path do %>
            <%= "修正" %>
          <% end %>
          <%=link_to book_path, method: :delete do %>
            <%= "削除" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= "ホーム" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= "ログアウト" %>
              <% end %>
            </li>
            <li>
              <%= link_to books_path do %>
                <%= "本一覧" %>
              <% end %>
            </li>
            <li>
              <%= link_to books_new_path do %>
                <%= "本の登録" %>
              <% end %>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= "登録" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= "ログイン" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>


<script>
  $(function(){
    $(".alert").fadeOut(5000);
  });
</script>

  </body>
</html>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Book Manager</h1>
    <h2 class="text-white">あなたの大切な本を管理しましょう</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to '登録', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'ログイン', login_path, class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">登録</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, "お名前", class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, "メールアドレス", class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
           <div class="form-group">
            <%= f.label :password, "パスワード", class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
           </div>
          <div class="form-group">
            <%= f.label :password_confirmation, "パスワード(確認用)", class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>